#!/bin/bash
#
# 1a. Make sure zsh is installed.
# 1b. Make sure git is installed.
# 1c. Make sure tmux is installed
# 1d. Make sure pip is installed.
# 2. Install oh-my-zsh from GitHub
# 3. Link appropriate dot-files
#
set -e

DEV_DIR="${HOME}/development"

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
elif [ "$system_type" = "Linux" ]; then
  distro=$(awk -F= '/^NAME/{print $2}' /etc/os-release)

  if [ $distro = \"Ubuntu\" ]; then
    sudo apt-get update

    sudo apt-get install -y zsh tmux git universal-ctags direnv \
      software-properties-common curl

    # Ubuntu has a really old version of Nvim so install it from upstream
    sudo add-apt-repository -y ppa:neovim-ppa/unstable
    sudo apt-get install -y neovim

    # Needed to build python
    sudo apt-get install -y build-essential checkinstall libreadline-dev \
    libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev \
        libbz2-dev libffi-dev liblzma-dev

    # WSL needs this or it will complain about locales endlessly
    sudo apt install locales
    sudo locale-gen en_US.UTF-8
    # sudo dpkg-reconfigure locales
  fi
fi

zsh --version 2>&1 /dev/null
if [ $? -eq 127 ]; then
  echo "Install ZSH!~"
  exit 1
fi

git --version 2>&1 /dev/null
if [ $? -eq 127 ]; then
  echo "Install Git!~"
  exit 1
fi

tmux -V 2>&1 /dev/null
if [ $? -eq 127 ]; then
  echo "Install Tmux!~"
  exit 1
fi

nvim -v 2>&1 /dev/null
if [ $? -eq 127 ]; then
  echo "Install nvim!~"
  exit 1
fi

direnv version
if [ $? -eq 127 ]; then
  echo "Install direnv!~"
  exit 1
fi

ctags --version
if [ $? -eq 127 ]; then
  echo "Install universal-ctags!~"
  exit 1
fi

# Install powerline-fonts
if [ ! -e ${HOME}/.fonts-installed ]; then
  echo "Installing powerline-fonts..."
  git clone https://github.com/powerline/fonts.git ${DEV_DIR}/fonts --depth=1
  if [ $? -ne 0 ]; then
    echo "Problem installing powerline-fonts"
    exit 1
  fi
  ${DEV_DIR}/fonts/install.sh
  rm -rf ${DEV_DIR}/fonts
  touch ~/.fonts-installed
fi

# Install tpm
if [ ! -e ${HOME}/.tmux/plugins/tpm ]; then
  echo "Installing tpm..."
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  if [ $? -eq 128 ]; then
    echo "Problem installing tpm."
    exit 1
  fi
fi

# Install oh-my-zsh
if [ ! -e ${DEV_DIR}/.oh-my-zsh ]; then
  echo "Installing oh-my-zsh..."
  git clone https://github.com/robbyrussell/oh-my-zsh.git ${DEV_DIR}/.oh-my-zsh
  if [ $? -eq 128 ]; then
    echo "Problem installing oh-my-zsh. Do you need to set a proxy?"
    exit 1
  fi
fi

# Install asdf
if [ ! -e ${HOME}/.asdf ]; then
  echo "Installing asdf..."
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  if [ $? -eq 128 ]; then
    echo "Problem installing asdf"
    exit 1
  fi
fi
source ~/.asdf/asdf.sh
set +e
asdf plugin add ruby
asdf plugin add java
asdf plugin add python
asdf plugin add golang
asdf plugin add nodejs
set -e
asdf install

# Prep vim-plug
if [ ! -e ${HOME}/.local/share/nvim/site/autoload/plug.vim ]; then
  echo 'Installing vim-plug...'
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  if [ $? -eq 128 ]; then
    echo "Problem installing vim-plug"
  fi
fi

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+GoInstallBinaries' '+CocInstall coc-json coc-tsserver' '+qall'
fi

# Prep starship
if [ ! -e /usr/local/bin/starship ]; then
  echo 'Installing starship...'
  curl -sS https://starship.rs/install.sh | sh
  if [ $? -eq 128 ]; then
    echo "Problem installing starship"
    exit 1
  fi
fi

# Change shell to zsh
sudo chsh -s /bin/zsh
